"use client";

import { useEffect, useRef, useState } from "react";
import { parseScene, type NodeSpec, type Scene } from "@t569/scene-engine";
import { prefersReducedMotion, runWhileVisible, themeColors, useThemeKey } from "@/lib/sceneTheme";

/**
 * The modular group tiling the upper half-plane.
 *
 * SL(2,ℤ) acts on H = {Im z > 0} by z ↦ (az + b)/(cz + d), generated by
 * T: z ↦ z + 1 and S: z ↦ −1/z. Its fundamental domain F = {|z| ≥ 1, |Re z| ≤ ½}
 * has one image under each group element (up to ±1), and those images tile H —
 * the picture behind modular forms, Marginalia vol. 1.
 *
 * Built as data: a breadth-first walk over words in S, T, T⁻¹ produces the
 * images ring by ring; each becomes a `polyline` whose stroke *draws itself*
 * (`animate.draw`) when its ring's turn comes. The whole construction is a
 * function of time, so the slider seeks it.
 */

type M = readonly [number, number, number, number]; // [a, b, c, d]
type Pt = readonly [number, number]; // (x, y) with y = Im z > 0

const mul = ([a, b, c, d]: M, [e, f, g, h]: M): M => [a * e + b * g, a * f + b * h, c * e + d * g, c * f + d * h];
const T: M = [1, 1, 0, 1];
const Ti: M = [1, -1, 0, 1];
const S: M = [0, -1, 1, 0];

/** ±g are the same map; key on the sign-normalised matrix. */
const key = (m: M) => {
	const s = m.find((v) => v !== 0)! < 0 ? -1 : 1;
	return m.map((v) => v * s).join(",");
};

/** (az + b)/(cz + d) for z = x + iy. */
function apply([a, b, c, d]: M, [x, y]: Pt): Pt {
	const nr = a * x + b;
	const ni = a * y;
	const dr = c * x + d;
	const di = c * y;
	const den = dr * dr + di * di;
	return [(nr * dr + ni * di) / den, (ni * dr - nr * di) / den];
}

/**
 * F split down the imaginary axis into its two halves — each a hyperbolic
 * triangle with angles π/2, π/3, 0. Shading one half and not the other gives the
 * classic two-coloured picture: the images of the halves are the (2,3,∞)
 * triangle tiling, where neighbours always differ. (Whole copies of F can't be
 * two-coloured — copies sharing a vertical side would have to match.)
 * Truncated at height TOP, since the cusp is at i∞.
 */
const TOP = 3;
const H3 = Math.sqrt(3) / 2;
function half(side: -1 | 1): Pt[] {
	const pts: Pt[] = [];
	for (let i = 0; i <= 10; i++) pts.push([0.5 * side, TOP - ((TOP - H3) * i) / 10]); // down the outer side to ρ or ρ+1
	for (let i = 1; i < 12; i++) {
		// along |z| = 1 from the corner (angle π/2 ∓ π/6) to i (angle π/2)
		const t = Math.PI / 2 - (side * Math.PI * (12 - i)) / 72;
		pts.push([Math.cos(t), Math.sin(t)]);
	}
	for (let i = 0; i <= 10; i++) pts.push([0, 1 + ((TOP - 1) * i) / 10]); // up the imaginary axis
	return pts;
}
const HALVES: Array<{ pts: Pt[]; shaded: boolean }> = [
	{ pts: half(-1), shaded: true },
	{ pts: half(1), shaded: false },
];

interface Tile {
	pts: Pt[];
	ring: number;
	shaded: boolean;
}

/** Breadth-first images of F, ring by ring, keeping those big enough to see. */
function tiles(maxRing: number, view: { x0: number; x1: number; y1: number }, minSize: number): Tile[] {
	const out: Tile[] = [];
	const seen = new Set<string>([key([1, 0, 0, 1])]);
	let frontier: M[] = [[1, 0, 0, 1]];
	for (let ring = 0; ring <= maxRing && frontier.length; ring++) {
		const next: typeof frontier = [];
		for (const m of frontier) {
			const images = HALVES.map((h) => ({ pts: h.pts.map((p) => apply(m, p)), shaded: h.shaded }));
			const all = images.flatMap((i) => i.pts);
			const xs = all.map((p) => p[0]);
			const ys = all.map((p) => p[1]);
			// Too small to see: drop it and everything reached through it.
			if (Math.max(Math.max(...xs) - Math.min(...xs), Math.max(...ys) - Math.min(...ys)) < minSize) continue;
			const inView = Math.max(...xs) > view.x0 && Math.min(...xs) < view.x1 && Math.min(...ys) < view.y1;
			if (inView) for (const img of images) out.push({ ...img, ring });
			for (const g of [T, Ti, S]) {
				const n = mul(m, g);
				const k = key(n);
				if (seen.has(k)) continue;
				seen.add(k);
				next.push(n);
			}
		}
		frontier = next;
	}
	return out;
}

const W = 800;
const H = 420;
const SCALE = 230; // scene units per unit of the plane
const toScene = ([x, y]: Pt): [number, number] => [W / 2 + x * SCALE, H - 18 - y * SCALE];

const RING_GAP = 0.55; // seconds between rings
const DURATION = 8;

export default function ModularTiling() {
	const hostRef = useRef<HTMLDivElement>(null);
	const sceneRef = useRef<Scene | null>(null);
	const [t, setT] = useState(DURATION);
	const [count, setCount] = useState(0);
	const themeKey = useThemeKey();

	useEffect(() => {
		const host = hostRef.current;
		if (!host) return;
		const { text, accent, muted } = themeColors(host);
		const view = { x0: -W / 2 / SCALE, x1: W / 2 / SCALE, y1: (H - 18) / SCALE };
		const list = tiles(9, view, 2 / SCALE);
		setCount(list.length);

		const objects: NodeSpec[] = [
			// The real axis: where every tile's cusps land.
			{ type: "path", d: `M0 ${H - 18} L${W} ${H - 18}`, stroke: muted, strokeWidth: 1 },
			...list.map(
				(tile): NodeSpec => ({
					type: "polyline",
					points: tile.pts.map(toScene),
					closed: true,
					fill: tile.shaded ? accent : "transparent",
					stroke: text,
					strokeWidth: 0.5,
					draw: 0,
					opacity: 0,
					animate: {
						draw: [{ at: tile.ring * RING_GAP, dur: 0.9, to: 1 }],
						opacity: [{ at: tile.ring * RING_GAP, dur: 0.6, to: tile.shaded ? 0.42 : 0.85 }],
					},
				}),
			),
		];

		const scene = parseScene({ width: W, height: H, objects }, host);
		sceneRef.current = scene;
		if (prefersReducedMotion()) {
			scene.seek(DURATION); // the finished picture, no construction
		} else {
			scene.seek(0);
			// Builds itself when scrolled to, not on page load.
			const stopWatching = runWhileVisible(host, scene);
			// Keep the slider in step while it plays, then hand time over to it.
			const tick = setInterval(() => {
				setT(Math.min(DURATION, scene.elapsed));
				if (scene.elapsed >= DURATION) {
					stopWatching();
					scene.stop();
					clearInterval(tick);
				}
			}, 100);
			return () => {
				stopWatching();
				clearInterval(tick);
				scene.destroy();
				sceneRef.current = null;
			};
		}
		return () => {
			scene.destroy();
			sceneRef.current = null;
		};
	}, [themeKey]);

	return (
		<figure className="m-0">
			<div ref={hostRef} className="w-full" style={{ aspectRatio: `${W} / ${H}` }} />
			<label className="mt-3 flex items-center gap-3 font-mono text-xs text-text-tertiary">
				<span>construct</span>
				<input
					type="range"
					min={0}
					max={DURATION}
					step={0.01}
					value={t}
					onChange={(e) => {
						const v = Number(e.target.value);
						setT(v);
						// Scrubbing takes time over from the clock for good.
						sceneRef.current?.stop();
						sceneRef.current?.seek(v);
					}}
					className="flex-1 accent-(--color-accent)"
					aria-label="Scrub the construction"
				/>
				<span>{count} tiles</span>
			</label>
		</figure>
	);
}
