/**
 * Every simulation, in one place: the lab page lists these, a post embeds one
 * with a ```sim fence, and the editor's simulation block picks from them.
 *
 * Data only, safe on the server. The code for each lives in Sim.tsx, and must: the
 * lab page is a server component, and a server module holding `import("./Mandelbrot")`
 * makes each scene a client reference shipped with the page — three.js and all,
 * up front. From the client, each loads only as it nears the screen. `aspect`
 * reserves the box before then, so nothing jumps.
 *
 * The words follow how explorable explanations teach: a question to hook the
 * reader, something to do with their hands, and the mathematics after, on
 * demand, for whoever wants it.
 */
export interface Sim {
	id: string;
	title: string;
	/** One line that makes the reader want to look. */
	hook: string;
	/** What to do with it. */
	tryThis: string;
	/** The mathematics, for after they've played. */
	maths: string;
	/** Roughly width / height, for the placeholder. Mounting starts well before the
	 *  box is on screen, so any difference settles out of sight. */
	aspect: number;
}

export const SIMS: Sim[] = [
	{
		id: "mandelbrot",
		title: "Into the Mandelbrot set",
		hook: "Ten thousand billion billion billion times down, the pattern hasn't run out.",
		tryThis: "Watch the dive to the minibrot at the bottom — or drag, pinch and scroll to go your own way. Switch the relief lighting and palettes along the bottom.",
		maths:
			"c belongs to the set when z ↦ z² + c, started at 0, never escapes. The dive ends at a minibrot of period 8007, 10³² times smaller than the set it copies. Ordinary floats run out of digits at 10¹⁵; this computes one reference orbit exactly and each pixel only its small difference from it (perturbation), skipping long stretches with linear approximations (BLA). Colour is the smoothed escape count, textured by the average angle of the last few steps (stripe colouring); the relief is lit from the potential's gradient.",
		aspect: 16 / 9,
	},
	{
		id: "puzzle",
		title: "Tune the ringing",
		hook: "Two numbers decide how a plucked string dies away. Can you find them?",
		tryThis: "Drag the sliders — or the dot — until your curve lies on the faint one.",
		maths:
			"A damped oscillation e^(−ax)·sin(bx): a sets how fast it dies, b how fast it rings. The whole puzzle, goal included, is a scene description with no code in it.",
		aspect: 640 / 420,
	},
	{
		id: "laplace",
		title: "The Laplace transform as a landscape",
		hook: "A whole signal, folded into two spikes on a plane.",
		tryThis: "Drag to turn the landscape. Follow the lit line as it sweeps, and see where it matches the fixed one.",
		maths:
			"f(t) = e^(−t/2)·sin(2t) rings and dies. Its transform F(s) = 2/((s + ½)² + 4), plotted as log|F| over the complex s-plane, rises in two spikes at s = −½ ± 2i: how fast f decays and how fast it rings is simply where those poles stand. The lit line sweeps Re s; the fixed one is Re s = 0, the Fourier transform.",
		aspect: 640 / 400,
	},
	{
		id: "lorenz",
		title: "One path through a vector field",
		hook: "Perfectly determined, never repeating: the shape that named the butterfly effect.",
		tryThis: "Drag to look around it while it draws. The bright dot is now; the faded path is its past.",
		maths:
			"The Lorenz system ẋ = σ(y − x), ẏ = x(ρ − z) − y, ż = xy − βz gives every point of space an arrow. A particle following them never settles, never repeats, and never leaves the butterfly. Integrated once with fourth-order Runge–Kutta.",
		aspect: 640 / 420,
	},
	{
		id: "modular",
		title: "The modular group tiles the half-plane",
		hook: "Two moves — shift and flip — are enough to tile an infinite plane.",
		tryThis: "Drag the slider to build the tiling one ring at a time.",
		maths:
			"SL(2,ℤ) moves the upper half-plane by z ↦ (az + b)/(cz + d), generated by a shift, z ↦ z + 1, and an inversion, z ↦ −1/z. Split its fundamental domain in two and the copies tile the plane in two colours. Each ring is one more letter in the word.",
		aspect: 800 / 480, // the scene plus its slider
	},
	{
		id: "flow",
		title: "A field made visible",
		hook: "The arrows are invisible. The streams they make are the picture.",
		tryThis: "Watch the eddies merge and part as the field itself drifts.",
		maths:
			"Hundreds of particles, each stepping along the arrow under it: v(x, y, t) = (sin(0.9y + 0.35t) + 0.55 cos(0.6x − 0.2t), cos(0.8x − 0.3t) + 0.55 sin(0.7y + 0.25t)). Two rotating families of waves, so the field has sinks, sources and swirls.",
		aspect: 12 / 7,
	},
	{
		id: "life",
		title: "The Game of Life",
		hook: "Two rules. From them: gliders, oscillators, and a gun that fires forever.",
		tryThis: "Draw on the board to add cells, or load the glider gun.",
		maths: "Survive with two or three live neighbours; be born with exactly three. Conway's rules are Turing-complete: the board can compute anything a computer can.",
		aspect: 96 / 58, // the board plus its buttons
	},
	{
		id: "fibonacci",
		title: "Fibonacci in a sunflower",
		hook: "Why do sunflowers count in Fibonacci numbers?",
		tryThis: "Nudge θ a fraction of a degree and watch the packing fall apart into spokes.",
		maths:
			"Seed n sits at angle n·θ, radius √n. At the golden angle, 137.508°, the seeds pack with no gaps, and the spirals you can see come in Fibonacci counts — because the golden ratio is the number worst approximated by fractions.",
		aspect: 1.2, // capped at max-w-md, plus its slider
	},
	{
		id: "fourier",
		title: "Circles all the way down",
		hook: "Any closed curve is a stack of spinning circles.",
		tryThis: "Move the slider: fewer circles, rougher heart.",
		maths: "Give each Fourier term a circle spinning at its frequency, stack them tip to tail, and the last tip draws the curve. The partial sums converge to it.",
		aspect: 520 / 480,
	},
	{
		id: "ad",
		title: "An ad, as data",
		hook: "No code — a whole animated banner is a description.",
		tryThis: "Watch the four-second loop; every part of it is a line of JSON.",
		maths: "A headline that pops, a rule that draws itself, a badge that pulses. Change the JSON and the campaign changes, without a deploy. What the engine was first built for.",
		aspect: 900 / 260,
	},
];

export const simById = (id: string): Sim | undefined => SIMS.find((s) => s.id === id.trim());
