/**
 * Every simulation, in one place: the lab page lists these, a post embeds one
 * with a ```sim fence, and the editor's simulation block picks from them.
 *
 * Data only, safe on the server. The code for each lives in Sim.tsx, and must: the
 * lab page is a server component, and a server module holding `import("./Mandelbrot")`
 * makes each scene a client reference shipped with the page — three.js and all,
 * up front. From the client, each loads only as it nears the screen. `aspect`
 * reserves the box before then, so nothing jumps.
 *
 * The words follow how explorable explanations teach: a question to hook the
 * reader, something to do with their hands, and the mathematics after, on
 * demand, for whoever wants it.
 */
export interface Sim {
	id: string;
	title: string;
	/** One line that makes the reader want to look. */
	hook: string;
	/** What to do with it. */
	tryThis: string;
	/** The mathematics, for after they've played. Markdown, formulas in $…$ LaTeX (KaTeX). */
	maths: string;
	/** Roughly width / height, for the placeholder. Mounting starts well before the
	 *  box is on screen, so any difference settles out of sight. */
	aspect: number;
}

export const SIMS: Sim[] = [
	{
		id: "mandelbrot",
		title: "Into the Mandelbrot set",
		hook: "Ten thousand billion billion billion times down, the pattern hasn't run out.",
		tryThis: "Watch the dive to the minibrot at the bottom — or drag, pinch and scroll to go your own way. Switch the relief lighting and palettes along the bottom.",
		maths:
			String.raw`$c$ belongs to the set when $z \mapsto z^2 + c$, started at $0$, never escapes. The dive ends at a minibrot of period 8007, $10^{32}$ times smaller than the set it copies. Ordinary floats run out of digits at $10^{15}$; this computes one reference orbit exactly and each pixel only its small difference from it (perturbation), skipping long stretches with linear approximations (BLA). Colour is the smoothed escape count, textured by the average angle of the last few steps (stripe colouring); the relief is lit from the potential's gradient.`,
		aspect: 16 / 9,
	},
	{
		id: "puzzle",
		title: "Tune the ringing",
		hook: "Two numbers decide how a plucked string dies away. Can you find them?",
		tryThis: "Drag the sliders — or the dot — until your curve lies on the faint one.",
		maths:
			String.raw`A damped oscillation $e^{-ax}\sin(bx)$: $a$ sets how fast it dies, $b$ how fast it rings. The whole puzzle, goal included, is a scene description with no code in it.`,
		aspect: 640 / 420,
	},
	{
		id: "laplace",
		title: "The Laplace transform as a landscape",
		hook: "A whole signal, folded into two spikes on a plane.",
		tryThis: "Drag to turn the landscape. Follow the lit line as it sweeps, and see where it matches the fixed one.",
		maths:
			String.raw`$f(t) = e^{-t/2}\sin(2t)$ rings and dies. Its transform $F(s) = \frac{2}{(s + \frac12)^2 + 4}$, plotted as $\log|F|$ over the complex $s$-plane, rises in two spikes at $s = -\tfrac12 \pm 2i$: how fast $f$ decays and how fast it rings is simply where those poles stand. The lit line sweeps $\operatorname{Re} s$; the fixed one is $\operatorname{Re} s = 0$, the Fourier transform.`,
		aspect: 640 / 400,
	},
	{
		id: "modular",
		title: "The modular group tiles the half-plane",
		hook: "Two moves — shift and flip — are enough to tile an infinite plane.",
		tryThis: "Drag the slider to build the tiling one ring at a time.",
		maths:
			String.raw`$\mathrm{SL}(2,\mathbb{Z})$ moves the upper half-plane by $z \mapsto \frac{az + b}{cz + d}$, generated by a shift, $z \mapsto z + 1$, and an inversion, $z \mapsto -1/z$. Split its fundamental domain in two and the copies tile the plane in two colours. Each ring is one more letter in the word.`,
		aspect: 800 / 480, // the scene plus its slider
	},
	{
		id: "delta",
		title: "A modular form as a landscape",
		hook: "One function, the same hills on every tile, forever shrinking toward the edge.",
		tryThis: "Scroll: the camera flies down over the central tiles and out to the rim, where the copies crowd. Every tile of the tiling above holds the same terrain.",
		maths:
			String.raw`The discriminant $\Delta(z) = q\prod_{n \ge 1}(1 - q^n)^{24}$, $q = e^{2\pi i z}$, is a modular form of weight 12: $\Delta\big(\frac{az + b}{cz + d}\big) = (cz + d)^{12}\,\Delta(z)$. So $y^6|\Delta(z)|$ is unchanged by the whole modular group, and plotted as height it repeats across every tile. Drawn on the Poincaré disk, the cusps become points on the rim, where the terrain sinks flat. Colour is the phase of $\Delta$. Each point is moved into the fundamental domain first, where $|q| < 0.005$ and eight factors of the product are exact.`,
		aspect: 640 / 440,
	},
	{
		id: "e4",
		title: "The first Eisenstein series",
		hook: "The simplest modular form there is: sum over every lattice point, and pits open where it vanishes.",
		tryThis: "Look for the dark pits: one at each corner of the fundamental domain, copied onto every tile. Toward the rim the hills level into a plateau.",
		maths: String.raw`$E_4(z) = 1 + 240\sum_{n \ge 1}\sigma_3(n)\,q^n$, with $\sigma_3(n)$ the sum of the cubes of $n$'s divisors, is a modular form of weight 4: up to a constant, $\sum (mz + n)^{-4}$ over every point of the lattice $\mathbb{Z}z + \mathbb{Z}$. The invariant height is $y^2|E_4(z)|$. Unlike $\Delta$ it is not a cusp form: $E_4 \to 1$ at the cusp, so its height grows there and is eased to a plateau. It has a single zero in the fundamental domain, at $\rho = e^{2\pi i/3}$, and $E_4(i) = 3\Gamma(\tfrac14)^8/(2\pi)^6 \approx 1.4558$; both are checked.`,
		aspect: 640 / 440,
	},
	{
		id: "e6",
		title: "The second Eisenstein series",
		hook: "Weight six: the pits move from the corners of the tiles to their tops.",
		tryThis: "Watch where the pits go: now one at the top of every tile, where E₄ had none.",
		maths: String.raw`$E_6(z) = 1 - 504\sum_{n \ge 1}\sigma_5(n)\,q^n$ has weight 6, and its height is $y^3|E_6(z)|$. Its zero sits at $z = i$, the point the inversion $z \mapsto -1/z$ fixes, so it must vanish there: $E_6(-1/z) = z^6 E_6(z)$ at $z = i$ gives $E_6(i) = -E_6(i)$. Together $E_4$ and $E_6$ generate every modular form: each one is a polynomial in them, $\Delta = (E_4^3 - E_6^2)/1728$ among them.`,
		aspect: 640 / 440,
	},
	{
		id: "jinv",
		title: "The j-invariant",
		hook: "One number for every shape of lattice: equal values, the same lattice turned.",
		tryThis: "The height is the same at every copy of a point, with no correction at all: j has weight zero. It shoots up toward the rim, where j has its pole.",
		maths: String.raw`$j(z) = 1728\,\frac{E_4^3}{E_4^3 - E_6^2} = \frac{E_4(z)^3}{\Delta(z)}$ is unchanged by the whole modular group, so its value names a lattice up to rotation and scaling: two lattices are similar exactly when their $j$s agree. It has a pole at the cusp ($j = q^{-1} + 744 + 196884\,q + \dots$, and 196884 is where moonshine begins), so the height is $\log(1 + |j|)$, levelled near the rim. $j(i) = 1728$ (the square lattice) and $j(\rho) = 0$ (the hexagonal one); both are checked.`,
		aspect: 640 / 440,
	},
	{
		id: "knots",
		title: "Every path on the modular surface, around a knot",
		hook: "Sixty-five thousand particles slide along the landscape above, and turn out to be living around a trefoil.",
		tryThis: "Drag to turn it. The white knot is where the landscape goes flat at the rim; the coloured loops are paths that come back to where they started.",
		maths:
			String.raw`A point of the modular surface with a direction is a lattice in the plane: shapes up to the modular group, sizes fixed. Send the lattice to its two Eisenstein invariants $(g_2, g_3)$ and the space of all of them is the 3-sphere with a trefoil removed ($g_2^3 = 27g_3^2$, where $\Delta = 0$: the cusp). Each particle follows its geodesic, a matrix multiplied a little every frame on the GPU and folded back into the fundamental domain. Ghys proved that the closed geodesics, drawn here, are knotted exactly like the periodic orbits of the Lorenz equations, next. Colour is the phase of $\Delta$, as on the landscape.`,
		aspect: 640 / 440,
	},
	{
		id: "torus",
		title: "Straight lines on a curved surface",
		hook: "Fire paths in every direction from one point. On the outside they meet again; in the hole they never do.",
		tryThis: "Click anywhere on the torus to fire from there. Drag to turn it. Try the warm outside, then the cool inside.",
		maths:
			String.raw`A geodesic is a path that never turns, as seen from the surface itself: $\ddot u^k + \Gamma^k_{ij}\,\dot u^i \dot u^j = 0$. On a torus with radii $R$ and $r$ the metric is $ds^2 = (R + r\cos v)^2\,du^2 + r^2\,dv^2$, and the Christoffel symbols $\Gamma$ tell each path how to bend with the surface. Colour is Gaussian curvature $K = \frac{\cos v}{r(R + r\cos v)}$: where $K > 0$ (warm), nearby geodesics bend toward each other and refocus — conjugate points; where $K < 0$ (cool), they spread apart exponentially. Each dot is stepped on the GPU with Runge–Kutta; the float64 reference keeps the speed and Clairaut's $(R + r\cos v)^2\,\dot u$ constant to $10^{-12}$.`,
		aspect: 640 / 440,
	},
	{
		id: "h3",
		title: "Inside hyperbolic space",
		hook: "Dodecahedra that meet at right angles: impossible here, and they fill the whole space there.",
		tryThis: "Drag to look around while you drift through it. Every cell is the same size; the far ones only look small.",
		maths:
			String.raw`Hyperbolic 3-space, seen from inside: the $\{5,3,4\}$ honeycomb, where regular dodecahedra meet four to an edge with right dihedral angles. Each pixel follows its geodesic in the hyperboloid model, $p(t) = \cosh t\,p + \sinh t\,d$ with $\langle p, p \rangle = -1$. Leaving the cell through a face, the ray is reflected in it and carries on, so one dodecahedron's twelve planes draw all of space. The number of cells within distance $r$ grows like $e^{2r}$: the edges dissolve into a haze of exponentially many cells, where flat space would show a few.`,
		aspect: 640 / 420,
	},
	{
		id: "sl2",
		title: "Inside the knot's complement",
		hook: "The space the particles above flow through, seen from inside: corridors that twist, and a glow where the knot is.",
		tryThis: "Drag to look around as you drift. Watch the colour along a wall: it turns as you move, because the space itself twists.",
		maths:
			String.raw`$\mathrm{SL}(2,\mathbb{R})$ geometry, one of Thurston's eight: the group of $2 \times 2$ matrices of determinant 1, with a metric that left multiplication preserves. Dividing by the modular group gives the unit tangent bundle of the modular surface — the 3-sphere minus the trefoil, where the particles above flow. Geodesics here are closed-form: $g \cdot \exp(t(X - cK)) \cdot \exp(tcK)$, the velocity turning about the fibre at twice its fibre component (checked by bending one and finding its length unchanged to first order). The walls are the modular tiling's edges, lifted along the fibres and coloured by the fibre's angle; the bright ends of the corridors are the cusp, where every lattice degenerates — the trefoil itself.`,
		aspect: 640 / 420,
	},
	{
		id: "s3",
		title: "Inside the 3-sphere",
		hook: "A space with no edge and no outside, where every straight line comes home.",
		tryThis: "Drag to look around. Find a ball that is far away but looks huge: it is past the equator, and its light is refocusing on you.",
		maths:
			String.raw`The 3-sphere, the unit sphere in four dimensions: finite, with no boundary. Its geodesics are great circles, $p(t) = \cos t\,p + \sin t\,d$, so a ray returns to your eye after $2\pi$, and you see every ball twice, once each way round. There is a ball at each vertex of the 24-cell — the 24 unit Hurwitz quaternions, nearest neighbours exactly $60^\circ$ apart. Beyond a quarter-turn away, things look bigger as they get farther: the lines from them reconverge toward you, as meridians do toward a pole.`,
		aspect: 640 / 420,
	},
	{
		id: "nil",
		title: "Inside Nil",
		hook: "Walk a loop and come back higher than you started, by exactly the area you went round.",
		tryThis: "Drag to look around. The stripes on the columns mark height; watch them slant as you look along a row.",
		maths:
			String.raw`Nil is the Heisenberg group: $(x, y, z) \cdot (x', y', z') = \big(x + x',\ y + y',\ z + z' + \tfrac12(xy' - yx')\big)$, with a metric left multiplication preserves. Its geodesics are helices, in closed form: seen from above, circles; and they climb. A horizontal loop rises by the area it encloses, the same twist that turns quantum mechanics' position and momentum into a Heisenberg pair. The columns stand on the integer grid; the stripes mark $z$. The first variation of length checks the helices are geodesics, and that their mirror images are not.`,
		aspect: 640 / 420,
	},
	{
		id: "sol",
		title: "Inside Sol",
		hook: "Go up, and one direction stretches while the other shrinks.",
		tryThis: "Drag to look up, then down. Amber sheets (x) thin out above you and crowd in below; blue (y) does the opposite.",
		maths:
			String.raw`Sol has the metric $ds^2 = e^{2z}dx^2 + e^{-2z}dy^2 + dz^2$: climbing $z$ stretches $x$ and squeezes $y$, and nothing in it is round. Its geodesics need elliptic functions, so each ray is stepped with Runge–Kutta through $x'' = -2x'z'$, $y'' = 2y'z'$, $z'' = e^{2z}x'^2 - e^{-2z}y'^2$, which keep $e^{2z}x'$ and $e^{-2z}y'$ fixed (checked to $10^{-14}$). The sheets are the coordinate planes $x, y, z \in \mathbb{Z}$: amber $x$, blue $y$, violet $z$.`,
		aspect: 640 / 420,
	},
	{
		id: "blackhole",
		title: "A black hole",
		hook: "The disk you see above the shadow is the far side, its light bent over the top.",
		tryThis: "Drag to fly over and under the disk. Watch the bright side: gas coming toward you, blueshifted.",
		maths:
			String.raw`Schwarzschild spacetime, mass $M = 1$. Light keeps to the plane of its position and direction, and there $u = 1/r$ obeys $u'' = -u + 3u^2$; the $3u^2$ is general relativity. Each pixel integrates it with Runge–Kutta, backwards from your eye. Rays with impact parameter below $3\sqrt3$ fall in: the shadow. Light can circle at $r = 3$, the photon sphere, giving the thin bright ring. The disk runs from the last stable orbit, $r = 6$, outward; its light is shifted by $g = \frac{\sqrt{1 - 3/r}}{1 - \Omega L}$ and brightened as $g^4$, so the approaching side blazes. Checked: the critical $3\sqrt3$, the photon sphere, and Einstein's $4M/b$ bending (with its second-order term).`,
		aspect: 640 / 420,
	},
	{
		id: "kerr",
		title: "A spinning black hole",
		hook: "Spin it up and the shadow stops being round.",
		tryThis: "Slide the spin from 0 to nearly 1. The shadow flattens on one side into a D, and the glowing gas creeps inward. Drag to fly over the pole.",
		maths:
			String.raw`The Kerr metric, mass $M = 1$, spin $a$. No orbit equation separates as neatly as Schwarzschild's, so each pixel integrates a whole photon geodesic as a Hamiltonian system in Boyer–Lindquist coordinates — $2\Sigma H = \Delta p_r^2 + p_\theta^2 + \big(\frac{L}{\sin\theta} - a\sin\theta\big)^2 - \frac{(r^2 + a^2 - aL)^2}{\Delta}$, and light has $H = 0$ — backwards from your eye with Runge–Kutta. Spacetime is dragged round with the spin, so light going with it can skim closer before being lost (the photon orbit at $r = 1.56$ for $a = 0.9$, against $3.91$ going the other way; Bardeen's values, checked). The gas is a thick torus emitting and absorbing along every ray, orbiting at $\Omega = \frac{1}{R^{3/2} + a}$, its light shifted by $g = \frac{1}{u^t(1 - \Omega L)}$ and brightened as $g^4$.`,
		aspect: 640 / 460, // the scene plus its slider
	},
	{
		id: "lorenz",
		title: "One path through a vector field",
		hook: "Perfectly determined, never repeating: the shape that named the butterfly effect.",
		tryThis: "Drag to look around it while it draws. The bright dot is now; the faded path is its past.",
		maths:
			String.raw`The Lorenz system $\dot x = \sigma(y - x)$, $\dot y = x(\rho - z) - y$, $\dot z = xy - \beta z$ gives every point of space an arrow. A particle following them never settles, never repeats, and never leaves the butterfly. Integrated once with fourth-order Runge–Kutta.`,
		aspect: 640 / 420,
	},
	{
		id: "flow",
		title: "A field made visible",
		hook: "The arrows are invisible. The streams they make are the picture.",
		tryThis: "Watch the eddies merge and part as the field itself drifts.",
		maths:
			String.raw`Hundreds of particles, each stepping along the arrow under it: $v(x, y, t) = \big(\sin(0.9y + 0.35t) + 0.55\cos(0.6x - 0.2t),\ \cos(0.8x - 0.3t) + 0.55\sin(0.7y + 0.25t)\big)$. Two rotating families of waves, so the field has sinks, sources and swirls.`,
		aspect: 12 / 7,
	},
	{
		id: "fluid",
		title: "Stir a fluid",
		hook: "Ink in water, solved forty thousand times a second.",
		tryThis: "Sweep the pointer through it. Fast strokes leave curls; slow ones barely ripple.",
		maths:
			String.raw`The incompressible Navier–Stokes equations, $\partial_t \mathbf u = -(\mathbf u \cdot \nabla)\mathbf u - \nabla p + \mathbf f$ with $\nabla \cdot \mathbf u = 0$, on a $128 \times 84$ grid. Each frame, on the GPU: put back the swirl that the grid smears out (vorticity confinement), solve for the pressure that makes the flow divergence-free (twenty Jacobi sweeps) and subtract its gradient, then carry velocity and ink along the flow by tracing each cell backwards — Stam's semi-Lagrangian step, stable at any time step. The ink lives on a finer $512 \times 336$ grid.`,
		aspect: 640 / 420,
	},
	{
		id: "life",
		title: "The Game of Life",
		hook: "Two rules. From them: gliders, oscillators, and a gun that fires forever.",
		tryThis: "Draw on the board to add cells, or load the glider gun.",
		maths: "Survive with two or three live neighbours; be born with exactly three. Conway's rules are Turing-complete: the board can compute anything a computer can.",
		aspect: 96 / 58, // the board plus its buttons
	},
	{
		id: "fibonacci",
		title: "Fibonacci in a sunflower",
		hook: "Why do sunflowers count in Fibonacci numbers?",
		tryThis: "Nudge θ a fraction of a degree and watch the packing fall apart into spokes.",
		maths:
			String.raw`Seed $n$ sits at angle $n\theta$, radius $\sqrt n$. At the golden angle, $137.508^\circ$, the seeds pack with no gaps, and the spirals you can see come in Fibonacci counts — because the golden ratio is the number worst approximated by fractions.`,
		aspect: 1.2, // capped at max-w-md, plus its slider
	},
	{
		id: "fourier",
		title: "Circles all the way down",
		hook: "Any closed curve is a stack of spinning circles.",
		tryThis: "Move the slider: fewer circles, rougher heart.",
		maths: "Give each Fourier term a circle spinning at its frequency, stack them tip to tail, and the last tip draws the curve. The partial sums converge to it.",
		aspect: 520 / 480,
	},
	{
		id: "ad",
		title: "Euler's identity, as data",
		hook: "Five constants, one equation, and not a line of code to animate it.",
		tryThis: "Watch the point walk half way round the circle; the identity assembles as it arrives. Then open the JSON: that is the whole scene.",
		maths: String.raw`$e^{i\theta} = \cos\theta + i\sin\theta$ is the point at angle $\theta$ on the unit circle. Turn by $\theta = \pi$ and it reaches $-1$, so $e^{i\pi} + 1 = 0$: $e$, $i$, $\pi$, $1$ and $0$ in one line. Here the circle draws itself, the point's position is an expression of the time, and each term pops in on cue, all as data. Change the JSON and the scene changes, without a deploy: what the engine was first built for.`,
		aspect: 900 / 260,
	},
	{
		id: "hero",
		title: "A 3D hero, as data",
		hook: "Glow, a galaxy, a headline — and still nothing but a description.",
		tryThis: "Watch the headline pop in. Then open the JSON: the 3D stage, the light, eleven and a half thousand drifting points, all of it is there.",
		maths:
			"The same idea as the banner above, carried into 3D: one WebGL canvas under the text, never two. Each point circles its own ring at a speed that falls off with radius, worked out on the GPU from the time alone, so the CPU does nothing per frame and the scene can be stopped at any instant. Under reduced motion that is what you get: one still frame, glow and all. three.js arrives only when the hero nears the screen.",
		aspect: 1200 / 500,
	},
];

export const simById = (id: string): Sim | undefined => SIMS.find((s) => s.id === id.trim());

/** The lab as a stage (LabChapters): the scenes in acts, each opened by a title card. */
export const ACTS: { title: string; sims: string[] }[] = [
	{ title: "Chaos & pattern", sims: ["mandelbrot", "lorenz", "flow", "fluid", "life", "fibonacci", "fourier"] },
	{ title: "Surfaces", sims: ["puzzle", "laplace", "torus"] },
	{ title: "The modular world", sims: ["modular", "delta", "e4", "e6", "jinv", "knots"] },
	{ title: "Inside geometries", sims: ["h3", "sl2", "s3", "nil", "sol"] },
	{ title: "Black holes", sims: ["blackhole", "kerr"] },
	{ title: "The engine", sims: ["ad", "hero"] }, // the coda
];

/** On the stage, these take every input once clicked (the wheel included); Esc gives it back. */
export const IMMERSIVE = new Set(["mandelbrot", "fluid", "h3", "sl2", "s3", "nil", "sol", "blackhole", "kerr"]);

/** Scenes driven by scroll, and how many screens their chapter lasts (ScrollProgress). */
export const SCROLL: Record<string, number> = { delta: 2.6 };

/**
 * On the stage, chapters that are one scene: mounted once (the first id's Sim) while any of them is
 * near, told which is on stage (StageChapter), and changed by the scene itself, not dissolved.
 */
export const GROUPS: string[][] = [["delta", "e4", "e6", "jinv"]];
export const groupOf = (id: string) => GROUPS.find((g) => g.includes(id));
