import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SITE } from "@/lib/constants";
import ModularTiling from "@/components/lab/ModularTiling";
import FourierEpicycles from "@/components/lab/FourierEpicycles";
import AdBanner from "@/components/lab/AdBanner";

export const metadata: Metadata = {
	title: "Lab",
	description: "Interactive scenes built on scene-engine: mathematics you can scrub, and an ad that is only data.",
};

/**
 * Interactive scenes — the scene engine's showroom on this site.
 *
 * Off unless NEXT_PUBLIC_SITE_LAB=true: upstream gets neither this page nor a
 * link to it.
 */
export default function LabPage() {
	if (!SITE.lab) notFound();

	return (
		<main className="mx-auto flex w-full max-w-4xl flex-col gap-16 px-4 py-12 md:px-6">
			<header className="flex flex-col gap-3">
				<p className="font-mono text-xs uppercase tracking-widest text-text-tertiary">Lab</p>
				<h1 className="font-display text-h1 font-bold text-text-primary">Scenes you can touch</h1>
				<p className="max-w-2xl text-body text-text-secondary">
					Everything here runs on{" "}
					<a href="https://github.com/t569/scene-engine" className="text-accent underline underline-offset-2">
						scene-engine
					</a>
					: an SVG scene graph with one clock, keyframes as data, and time you can scrub. The same parts
					draw the Klein bottle on the About page, the chat character in the corner, and ads.
				</p>
			</header>

			<section className="flex flex-col gap-4">
				<h2 className="font-display text-h3 font-semibold text-text-primary">The modular group tiles the half-plane</h2>
				<p className="max-w-2xl text-sm leading-relaxed text-text-secondary">
					SL(2,ℤ) moves the upper half-plane by z ↦ (az + b)/(cz + d), generated by a shift, z ↦ z + 1,
					and an inversion, z ↦ −1/z. One region — the arch above the unit circle between Re z = ±½ —
					has exactly one copy under every element, and the copies fill the plane. Each ring of tiles is
					one more letter in the word. Drag the slider to build it by hand.
				</p>
				<ModularTiling />
			</section>

			<section className="flex flex-col gap-4">
				<h2 className="font-display text-h3 font-semibold text-text-primary">Circles all the way down</h2>
				<p className="max-w-2xl text-sm leading-relaxed text-text-secondary">
					Any closed curve is a sum of rotations. Take its Fourier transform, give each term a circle
					spinning at its frequency, stack them tip to tail, and the last tip draws the curve. Fewer
					circles, rougher heart — move the slider and watch it converge.
				</p>
				<FourierEpicycles />
			</section>

			<section className="flex flex-col gap-4">
				<h2 className="font-display text-h3 font-semibold text-text-primary">An ad, as data</h2>
				<p className="max-w-2xl text-sm leading-relaxed text-text-secondary">
					No code below — only a scene description. A headline that pops, a rule that draws itself, a
					badge that pulses, looping every four seconds. Change the JSON and the campaign changes, with
					no deploy. That is what the engine was first built for.
				</p>
				<AdBanner />
			</section>
		</main>
	);
}
