import type { Metadata } from "next";
import type { ComponentType } from "react";
import { notFound } from "next/navigation";
import { SITE } from "@/lib/constants";
import CurvePuzzle from "@/components/lab/CurvePuzzle";
import ModularTiling from "@/components/lab/ModularTiling";
import LaplaceSurface from "@/components/lab/LaplaceSurface";
import LorenzAttractor from "@/components/lab/LorenzAttractor";
import FlowField from "@/components/lab/FlowField";
import Mandelbrot from "@/components/lab/Mandelbrot";
import GameOfLife from "@/components/lab/GameOfLife";
import Phyllotaxis from "@/components/lab/Phyllotaxis";
import FourierEpicycles from "@/components/lab/FourierEpicycles";
import AdBanner from "@/components/lab/AdBanner";

export const metadata: Metadata = {
	title: "Lab",
	description:
		"Interactive mathematics on scene-engine: puzzles you solve by dragging, surfaces you can orbit, fractals, fields, and an ad that is only data.",
};

interface Exhibit {
	id: string;
	title: string;
	/** What to look at, and what to try. */
	blurb: string;
	Scene: ComponentType;
}

const EXHIBITS: Exhibit[] = [
	{
		id: "puzzle",
		title: "Tune the ringing",
		blurb:
			"A damped oscillation e^(−ax)·sin(bx): a sets how fast it dies, b how fast it rings. Drag the sliders — or the dot — until your curve lies on the faint one. The whole puzzle, goal included, is a scene description with no code in it.",
		Scene: CurvePuzzle,
	},
	{
		id: "modular",
		title: "The modular group tiles the half-plane",
		blurb:
			"SL(2,ℤ) moves the upper half-plane by z ↦ (az + b)/(cz + d), generated by a shift, z ↦ z + 1, and an inversion, z ↦ −1/z. Split its fundamental domain in two and the copies tile the plane in two colours. Each ring is one more letter in the word; drag the slider to build it by hand.",
		Scene: ModularTiling,
	},
	{
		id: "laplace",
		title: "The Laplace transform as a landscape",
		blurb:
			"f(t) = e^(−t/2)·sin(2t) rings and dies. Its transform F(s) = 2/((s + ½)² + 4), plotted as log|F| over the complex s-plane, rises in two spikes at s = −½ ± 2i: how fast f decays and how fast it rings is simply where those poles stand. The lit line sweeps Re s; at Re s = 0 it is the Fourier transform. Drag to turn it.",
		Scene: LaplaceSurface,
	},
	{
		id: "lorenz",
		title: "One path through a vector field",
		blurb:
			"The Lorenz system gives every point of space an arrow. A particle following them never settles, never repeats, and never leaves the butterfly. Drag to look around it while it draws.",
		Scene: LorenzAttractor,
	},
	{
		id: "flow",
		title: "A field made visible",
		blurb:
			"Hundreds of particles, each following the arrow under it. The arrows are invisible; the streams they make are the picture — and the field itself drifts, so the eddies merge and part.",
		Scene: FlowField,
	},
	{
		id: "mandelbrot",
		title: "Into the Mandelbrot set",
		blurb:
			"c belongs when z ↦ z² + c, started at 0, never escapes. This dives into Seahorse Valley by a factor of e every three seconds, and the boundary never runs out of detail. Colours are escape times, in whatever palette you've picked.",
		Scene: Mandelbrot,
	},
	{
		id: "life",
		title: "The Game of Life",
		blurb:
			"Survive with two or three live neighbours; be born with exactly three. From that: gliders, oscillators, and Gosper's gun firing gliders for ever. Draw on the board to add cells.",
		Scene: GameOfLife,
	},
	{
		id: "fibonacci",
		title: "Fibonacci in a sunflower",
		blurb:
			"Seed n sits at angle n·θ, radius √n. At the golden angle, 137.508°, the seeds pack with no gaps, and the spirals you can see come in Fibonacci counts. Nudge θ a fraction of a degree and it falls apart into spokes.",
		Scene: Phyllotaxis,
	},
	{
		id: "fourier",
		title: "Circles all the way down",
		blurb:
			"Any closed curve is a sum of rotations. Give each Fourier term a circle spinning at its frequency, stack them tip to tail, and the last tip draws the curve. Fewer circles, rougher heart — move the slider and watch it converge.",
		Scene: FourierEpicycles,
	},
	{
		id: "ad",
		title: "An ad, as data",
		blurb:
			"No code — only a scene description: a headline that pops, a rule that draws itself, a badge that pulses, on a four-second loop. Change the JSON and the campaign changes, without a deploy. What the engine was first built for.",
		Scene: AdBanner,
	},
];

/**
 * Interactive scenes — the scene engine's showroom on this site.
 *
 * Off unless NEXT_PUBLIC_SITE_LAB=true: upstream gets neither this page nor a
 * link to it. Every scene animates only while on screen.
 */
export default function LabPage() {
	if (!SITE.lab) notFound();

	return (
		<main className="mx-auto flex w-full max-w-4xl flex-col gap-16 px-4 py-12 md:px-6">
			<header className="flex flex-col gap-3">
				<p className="font-mono text-xs uppercase tracking-widest text-text-tertiary">Lab</p>
				<h1 className="font-display text-h1 font-bold text-text-primary">Scenes you can touch</h1>
				<p className="max-w-2xl text-body text-text-secondary">
					Mathematics to play with. Built on{" "}
					<a href="https://github.com/t569/scene-engine" className="text-accent underline underline-offset-2">
						scene-engine
					</a>{" "}
					— one clock, keyframes and formulas as data, time you can scrub — plus a canvas runtime for the
					pixel-heavy ones. The same parts draw the Klein bottle on the About page and the character in the
					corner.
				</p>
				<nav aria-label="Exhibits" className="flex flex-wrap gap-2 pt-2">
					{EXHIBITS.map((e) => (
						<a
							key={e.id}
							href={`#${e.id}`}
							className="rounded-full border border-border-subtle px-3 py-1 font-mono text-[0.7rem] text-text-secondary hover:border-accent hover:text-accent"
						>
							{e.title}
						</a>
					))}
				</nav>
			</header>

			{EXHIBITS.map(({ id, title, blurb, Scene }) => (
				<section key={id} id={id} className="flex scroll-mt-24 flex-col gap-4">
					<h2 className="font-display text-h3 font-semibold text-text-primary">{title}</h2>
					<p className="max-w-2xl text-sm leading-relaxed text-text-secondary">{blurb}</p>
					<Scene />
				</section>
			))}
		</main>
	);
}
